@baseAddress = http://localhost:5081

GET {{baseAddress}}/api/categories
Accept: application/json

###
Post {{baseAddress}}/api/categories
Accept: application/json
{
  "name":"Category 1",
  "description":"Category 1 description"
}
###
